# TODO: replace the title with the name of your restaurant!
title: "CAFE COKU"
# TODO: write your restaurateur alter ego name below, or your own name
author: Manasvi
# TODO: write your Google Analytics tracking ID below
google_analytics: G-FY7TL4YVWQ

theme: minima

collections:
  explorations:
    output: true
